config/routes.rb
Rails.application.routes.draw do

  resources :wikis do
    resources :collaborations, only: [:index, :create, :destroy]
  end
  
  resources :charges, only: [:new, :create,]
  
  get 'charges/downgrade', :to => 'charges#downgrade'
  
  devise_for :users
  
  
  get 'welcome/index'

  get 'welcome/about'
  
  root to: 'welcome#index'

end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :wiki
  
  def self.users
    User.where( id: pluck(:user_id) )  
  end
  
  def self.wikis
    Wiki.where( id: pluck(:wiki_id) )
  end
  
  def wiki
    Wiki.find(wiki_id)
  end
  
  def user
    User.find(user_id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  before_save { self.role ||= :standard }
  
  has_many :collaborations
  has_many :wikis
  
  enum role: [:standard, :premium, :admin]
  
  def standard?
    role == "standard"
  end
  
  def premium?
    role == "premium"
  end
  
  def admin?
    role == "admin"
  end
  
  #def collaborated_on
    #Collaboration.where(user_id: id)
  #end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborations
  has_many :users, through: :collaborations
  
  #def collaborations
    #Collaboration.where(wiki_id: id)
  #end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  
  class Amount
    def self.default
      15_00
    end
  end
  
  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )
    
    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: Amount.default,
      description: "Premium Membership - #{current_user.email}",
      currency: 'usd'
    )
    
    flash[:notice] = "Thanks for supporting the site, #{current_user.email}! Feel free to create private wikis."
    current_user.premium!
    redirect_to wikis_path(current_user)
    
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
  end
  
  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Premium Membership - #{current_user.email}",
      amount: Amount.default
    }
  end
  
  def downgrade
    current_user.standard!
    current_user.wikis.update_all(private: false)
    redirect_to root_path
  end
end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController
  before_action :set_wiki
  
  def create
    @collaboration = @wiki.collaborations.new(user_id: params[:user_id])
    
    if @collaboration.save
      flash[:notice] = "Collaborator was added."
      redirect_to wiki_collaborations_path
    else
      flash[:error] = "Collaborator was not added."
      render wiki_collaborations_path
    end
  end

  def destroy
    @collaboration = @wiki.collaborations.find_by(user_id: params[:id])

    if @collaboration.destroy
      flash[:notice] = "Collaborator has been removed."
      redirect_to wiki_collaborations_path
    else
      flash[:error] = "Whoops!"
    end
  end
  
  def index
    #use devise for this authenticating
    if @wiki.user_id == current_user.id
      @users = User.all
    else
      redirect_to wikis_path
    end
  end
  
  def set_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = current_user
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :set_wiki, only: [:show, :edit, :update, :destroy]

  # GET /wikis
  # GET /wikis.json
  def index
    @wikis = policy_scope(Wiki)
  end

  # GET /wikis/1
  # GET /wikis/1.json
  def show
  end

  # GET /wikis/new
  def new
    @wiki = Wiki.new
  end

  # GET /wikis/1/edit
  def edit
  end

  # POST /wikis
  # POST /wikis.json
  def create
    @wiki = current_user.wikis.new(wiki_params)

    respond_to do |format|
      if @wiki.save
        format.html { redirect_to @wiki, notice: 'Wiki was successfully created.' }
        format.json { render :show, status: :created, location: @wiki }
      else
        format.html { render :new }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wikis/1
  # PATCH/PUT /wikis/1.json
  def update
    respond_to do |format|
      if @wiki.update(wiki_params)
        format.html { redirect_to @wiki, notice: 'Wiki was successfully updated.' }
        format.json { render :show, status: :ok, location: @wiki }
      else
        format.html { render :edit }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wikis/1
  # DELETE /wikis/1.json
  def destroy
    @wiki.destroy
    respond_to do |format|
      format.html { redirect_to wikis_url, notice: 'Wiki was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wiki
      @wiki = Wiki.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wiki_params
      params.require(:wiki).permit(:title, :body, :private)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = { fenced_code_blocks: true }
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborations_helper.rb
module CollaborationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/downgrade.html.erb
<p>You have downgraded to <%= current_user.role %></p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click to upgrade to <strong>premium</strong>   and make private wikis!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
  <h3>Want to downgrade to standard?</h3> 
  <%= link_to 'Downgrade', charges_downgrade_path, :class => 'btn btn-primary', data: { confirm: "Are you sure?" }, :class => 'btn btn-warning' %>
<% end %>

app/views/collaborations/create.html.erb
<h1>Collaborations#create</h1>
<p>Find me in app/views/collaborations/create.html.erb</p>

app/views/collaborations/destroy.html.erb
<h1>Collaborations#destroy</h1>
<p>Find me in app/views/collaborations/destroy.html.erb</p>

app/views/collaborations/index.html.erb
<table>
   
<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td>
      <% if @wiki.users.include?(user) %>
        <%= link_to "Remove", wiki_collaboration_path(@wiki, user, remove: true), method: :delete, class: "btn btn-danger" %>
      <% else %>
        <%= link_to "Add Collaborator", wiki_collaborations_path(@wiki, user_id: user.id), method: :post, class: "btn btn-success" %>
      <% end %>
    </td>
    
  </tr>
<% end %>
</table>

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Universalpedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <ul class="nav nav-tabs">
    <% if user_signed_in? %>
       <div class='pull-right control-group'>Signed in as: <strong><%= current_user.email %></strong></div> 
      <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li> 
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
      <li><%= link_to 'New Wiki', new_wiki_path, :class => 'navbar-link' %></li>
      <li><%= link_to 'All Wikis', wikis_path, :class => 'navbar-link' %></li>
      <li><%= link_to 'About Us', welcome_about_path, :class => 'navbar-link' %></li>
      <li><%= link_to 'Upgrade', new_charge_path, :class => 'navbar-link' %></li>
    <% else %>
      <li><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %></li>
      <li><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %></li>
    <% end %>
  </ul>
  <div class="flash">  
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <% flash[:error] %>
      </div>
    <% end %>
  </div>
<%= yield %>
</div>
</body>
</html>

app/views/welcome/about.html.erb
<h1>About Our Project</h1>
<p>Universalpedia is an app that allows users to create a wiki for whatever subject they are interested in</p>

app/views/welcome/index.html.erb
<h1>Universalpedia</h1>
<p>You are a <%= @user.role %> member!</p>

app/views/wikis/_form.html.erb
<%= form_for(@wiki) do |f| %>
  <% if @wiki.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wiki.errors.count, "error") %> prohibited this wiki from being saved:</h2>

      <ul>
      <% @wiki.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <% if current_user.premium? || current_user.admin? %>
  <div class="field">
    <%= f.label :private %><br>
    <%= f.check_box :private %>
  </div>
  <% end %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Editing Wiki</h1>

<%= render 'form' %>

<%= link_to "Manage Collaborations", wiki_collaborations_path(@wiki) %> |

<%= link_to 'Show', @wiki %> |
<%= link_to 'Back', wikis_path %>

app/views/wikis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Universal Wikis</h1>
<div class="progress progress-success">
  <div class="progress-bar" style="width: 100%"></div>
</div>
  <% @wikis.each do |wiki| %>
  <h4><strong>Title</strong>: <%= wiki.title %></h4>
  <p><strong>Body</strong>: <%= wiki.body %></p>
  <p><%= wiki.private %></p>
  <%= link_to 'Show', wiki, class: "btn btn-default btn-xs" %>
  <%= link_to 'Edit', edit_wiki_path(wiki), class: "btn btn-default btn-xs"  %>
  <%= link_to 'Destroy', wiki, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-xs"  %>
  <% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<%= render 'form' %>

<%= link_to 'Back', wikis_path %>

app/views/wikis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title: </strong>
  <%= markdown_to_html(@wiki.title) %>
</p>

<p>
  <strong>Body:</strong>
  <%= markdown_to_html(@wiki.body) %>
</p>

<p>
  <strong>Private:</strong>
  <%= @wiki.private %>
</p>



<%= link_to 'Edit', edit_wiki_path(@wiki) %> |
<%= link_to 'Back', wikis_path %>